extensions:

receivers:
  telemetrygen:
    throughput: 1048576 # 1MB (1024*1024)

processors:

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [telemetrygen]
      processors:
      exporters: [debug]
    logs:
      receivers: [telemetrygen]
      processors:
      exporters: [debug]
    traces:
      receivers: [telemetrygen]
      processors:
      exporters: [debug]
