// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("telemetrygen")
	ScopeName = "github.com/rogercoll/telemetrygen"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
